ValueSet: VS_TMLT_eClaim_LabFU
Id: vs-tmlt-eclaim-labfu
Title: "ValueSet: รหัสการตรวจทางห้องปฏิบัติการ TMLT ที่ใช้ในแฟ้ม LABFU (e-Claim)"
Description: "รหัสการตรวจทางห้องปฏิบัติการ TMTL ที่ใช้ในแฟ้ม LABFU (e-Claim)"
* ^url = $VS_TMLT_eClaim_LabFU
* $CS_TMLT#320281 "Fasting glucose [mg/dL] in Venous blood"
* $CS_TMLT#320062 "Glucose [mg/dL] in Serum or Plasma"
* $CS_TMLT#320280 "Fasting glucose [mg/dL] in Capillary blood"
* $CS_TMLT#320064 "Glucose [mg/dL] in Capillary blood"
* $CS_TMLT#320131 "Hemoglobin A1c/Hemoglobin.total [%] in Blood"
* $CS_TMLT#320072 "Triglyceride [mg/dL] in Serum or Plasma"
* $CS_TMLT#320070 "Cholesterol [mg/dL] in Serum or Plasma"
* $CS_TMLT#320071 "Cholesterol in HDL [mg/dL] in Serum or Plasma"
* $CS_TMLT#320073 "Cholesterol in LDL [mg/dL] in Serum or Plasma by Direct assay"
* $CS_TMLT#320052 "Urea nitrogen [mg/dL] in Serum or Plasma"
* $CS_TMLT#320123 "Creatine kinase [U/L] in Serum or Plasma"
* $CS_TMLT#320269 "Microalbumin [mg/dL] in Urine by Test strip"
* $CS_TMLT#320057 "Creatinine [mg/dL] in Urine"
* $CS_TMLT#310001 "Albumin [+/-] in Urine by Test strip"
* $CS_TMLT#390001 "Glomerular filtration rate/1.73 sq M.predicted [mL/min/1.73 sq M] in Serum, Plasma or Blood by Creatinine-based formula (CKD-EPI)"
* $CS_TMLT#300089 "Hemoglobin [g/dL] in Blood"
* $CS_TMLT#320483 "Protein/Creatinine [mg/gm cr] in Urine"
* $CS_TMLT#320026 "Potassium [mmol/L] in Serum or Plasma"
* $CS_TMLT#320489 "Bicarbonate [mmol/L] in Venous blood"
* $CS_TMLT#320022 "Phosphate [mg/dL] in Serum or Plasma"
* $CS_TMLT#320216 "Parathyrin.intact [pg/mL] in Serum or Plasma"